config/routes.rb
Rails.application.routes.draw do
  
  get    'presences/index'
  post   'presences/index' => 'presences#create'
  get    'presences/new'
  get    'presences/edit'
  post    'presences/edit' => 'presences#update'
  
  get 'home/indexx'

  resources :subjects

  devise_for :users
  
  resources :students

  resources :courses

  root 'home#indexx'

end
=begin
C:\Bitnami\rubystack2\projects\after_school>rake routes

                  Prefix Verb   URI Pattern                    Controller#Action

    resences_index_path         GET   /presences/index(.:format)  presences#index
    presences_insert_path       POST  /presences/insert(.:format) presences#insert
    presences_modify_path       GET   /presences/modify(.:format) presences#modify
    presences_destroy_path      GET   /presences/destroy(.:format)  presences#destroy

    home_index_path             GET    /home/index(.:format)      home#index

      subjects_path   GET   /subjects(.:format)         subjects#index
                      POST  /subjects(.:format)         subjects#create
    new_subject_path  GET   /subjects/new(.:format)     subjects#new
    edit_subject_path GET   /subjects/:id/edit(.:format) subjects#edit
    subject_path      GET   /subjects/:id(.:format)     subjects#show
                      PATCH /subjects/:id(.:format)     subjects#update
                      PUT /subjects/:id(.:format)       subjects#update
                      DELETE  /subjects/:id(.:format)   subjects#destroy
   
   new_user_session GET    /users/sign_in(.:format)       devise/sessions#new
       user_session POST   /users/sign_in(.:format)       devise/sessions#create
destroy_user_session DELETE /users/sign_out(.:format)      devise/sessions#destroy

      user_password POST   /users/password(.:format)      devise/passwords#create
  new_user_password GET    /users/password/new(.:format)  devise/passwords#new
 edit_user_password GET    /users/password/edit(.:format) devise/passwords#edit
                    PATCH  /users/password(.:format)      devise/passwords#update
                    PUT    /users/password(.:format)      devise/passwords#update

cancel_user_registration GET    /users/cancel(.:format)        devise/registrations#cancel
       user_registration POST   /users(.:format)               devise/registrations#create
   new_user_registration GET    /users/sign_up(.:format)       devise/registrations#new
  edit_user_registration GET    /users/edit(.:format)          devise/registrations#edit
                         PATCH  /users(.:format)               devise/registrations#update
                         PUT    /users(.:format)               devise/registrations#update
                         DELETE /users(.:format)               devise/registrations#destroy

    students GET    /students(.:format)          students#index
             POST   /students(.:format)          students#create
 new_student GET    /students/new(.:format)      students#new
edit_student GET    /students/:id/edit(.:format) students#edit
     student GET    /students/:id(.:format)      students#show
             PATCH  /students/:id(.:format)      students#update
             PUT    /students/:id(.:format)      students#update
             DELETE /students/:id(.:format)      students#destroy

     courses GET    /courses(.:format)           courses#index
             POST   /courses(.:format)           courses#create
  new_course GET    /courses/new(.:format)       courses#new
 edit_course GET    /courses/:id/edit(.:format)  courses#edit
      course GET    /courses/:id(.:format)       courses#show
             PATCH  /courses/:id(.:format)       courses#update
             PUT    /courses/:id(.:format)       courses#update
             DELETE /courses/:id(.:format)       courses#destroy
=end

app/models/presence.rb
class Presence < ActiveRecord::Base
  belongs_to :student
  has_one :course, through: :student
  belongs_to :user

  has_and_belongs_to_many :subjects

  validates :student_id, presence: true
  validates :date, presence: true
  validates :student_id, uniqueness: { scope: :date, message: "should happen once per day" }
  validates :user_id, presence: true
end

app/controllers/presences_controller.rb
class PresencesController < ApplicationController
  before_action :set_params, only: [:new, :edit]
  before_action :authenticate_user!
  
  def index
  end

  def new
  	redirect_to presences_edit_path(params) and return if params[:modify_button]
  	destroy if params[:destroy_button] #and return
  	redirect_to presences_index_path, notice: 'Presences already created.' and return if !set_presences.empty? 
  		
    students = Student.where(course_id: params[:course_id]).order(:surname, :name)
	@presences = []
	students.each do |student| 
	   @presences.push Presence.new(student_id: student.id, date: Date.parse(params[:date]))
	end
  end

  def create
  	params[:presences].values.each do |presence_data|
  		presence = Presence.new(
  			student_id: presence_data[:student_id],
  			date:       presence_data[:date],
  			absent:     presence_data[:absent],
  			user_id:    current_user.id,
  			note:       presence_data[:note],
  		)
  		presence.save
  		subjects_array = presence_data[:subject_ids].drop(1)
  		subjects_array.each do |sub_id|
  			PresencesSubjects.create(presence_id: presence.id, subject_id: sub_id)
  		end
    end
  	redirect_to presences_index_path, notice: 'Presences was successfully created.'
  end

  def edit
    @presences = set_presences
    redirect_to presences_index_path, notice: "Presences doesn't exists." and return if @presences.empty? 
  end

  def update
   	params[:presences].values.each do |presence_data|
  		presence = Presence.find(presence_data[:id])
   		presence.update(absent: presence_data[:absent], note: presence_data[:note])
  		
  		PresencesSubjects.where(presence_id: presence.id).delete_all
  		subjects_array = presence_data[:subject_ids].drop(1)
  		subjects_array.each do |sub_id|
  			PresencesSubjects.create(presence_id: presence.id, subject_id: sub_id)
  		end
  	end
  	redirect_to presences_index_path, notice: "Presences was successfully updated."
  end

  def destroy
	presences = set_presences
	redirect_to presences_index_path, notice: "Presences doesn't exists." and return if presences.empty? 
	
	presences.each do |presence|
		PresencesSubjects.where(presence_id: presence.id).delete_all
	end
	presences.delete_all
  	redirect_to presences_index_path, notice: "Presences was successfully deleted."
  end

private

  def set_params
    params.permit(:course_id, :date)
    @course = Course.find(params[:course_id])
    @date = Date.parse(params[:date]).strftime("%a %e %b %Y")
  end

  def set_presences
  	Presence.joins(:student).where(students: {course_id: params[:course_id]},
												   date: params[:date])
  end

end

app/helpers/presences_helper.rb
module PresencesHelper
end

app/views/presences/_form.html.erb
<table>
  <thead>
    <tr>
      <th>Nr</th>
      <th>SurName</th>
      <th>Name</th>
      <th>Awaited<br>today</th>
      <th>Absent</th>
      <th>Subjects Incomplete</th>
      <th>Note</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>

<% if params[:modify_button] %>
<%   args = presences_edit_path(@presences) %>
<% else %>
<%   args = presences_index_path(@presences) %>
<% end %>
<%=  form_tag args do |f|  %>

<% if @presences  %>
  <% @presences.each_with_index do |presence, index| %> 
    <tr>
      <%= fields_for "presences[#{index}]", presence do |pf| %>
        <td><%= index+1 %></td>
        <td><%= presence.student.surname %></td>
        <td><%= presence.student.name %></td>
<% awaited = case @date[0..2] %>
<% when "Mon" then presence.student.awaited_Mon %>
<% when "Tue" then presence.student.awaited_Tue %>
<% when "Wed" then presence.student.awaited_Wed %>
<% when "Thu" then presence.student.awaited_Thu %>
<% when "Fri" then presence.student.awaited_Fri %>
<% when "Sat" then presence.student.awaited_Sat %>
<% when "Sun" then presence.student.awaited_Sun %>
<% end %>
        <td><%= check_box_tag :awaited, nil, awaited, disabled: true %></td>

        <td><%= pf.check_box :absent %></td>
        <td><%= pf.select :subject_ids, options_from_collection_for_select(Subject.all, :id, :name, presence.subjects.map { |s| s.id }), {include_blank: true}, multiple: true %>
        <td><%= pf.text_area :note, rows: 4 %></td>
        <td><%= pf.hidden_field :student_id, value: presence.student_id %></td>
        <td><%= pf.hidden_field :date, value: presence.date %></td>
        <td><%= pf.hidden_field :id, value: presence.id %></td>
      <% end %>
    </tr>
  <% end %>
    <tr>
      <td><%= submit_tag "Save" %></td>
    </tr>  
<% end %>
<% end %>

  </tbody>
</table>

app/views/presences/edit.html.erb
<h1>Editing Presences</h1>
<h2><%= "Edit presences of course #{@course.name} in date #{@date}"%></h2>

<%= render 'form' %>

<%= link_to 'Back', presences_index_path %>

app/views/presences/index.html.erb
<% if notice %>
  <div id="error_explanation">
    <ul>
      <li><%= notice %></li>
    </ul>
  </div>
<% end %>

<h1>Listing presences</h1>

<p>Scegli che presenze vuoi modificare</p>
<%= form_tag presences_new_path, method: :get  %>
  <div class="field">
    <%= label_tag :course_id %><br>
    <%= select_tag :course_id, options_from_collection_for_select(Course.all, :id, :name)  %>
  </div>
  <div class="field">
    <%= label_tag :date %><br>
    <%= date_field_tag :date, value = Date.today %>
  </div>
  <div class="actions">
    <%= submit_tag "Insert" %>
    <%= submit_tag "Modify", name: 'modify_button' %>
    <%= submit_tag "Destroy", name: 'destroy_button', data: {confirm: 'Are you sure?'} %>
  </div>
</form>

app/views/presences/new.html.erb
<h1>Insert Presences</h1>
<h2><%= "Insert presences of course #{@course.name} in date #{@date}"%></h2>

<%= render 'form' %>

<%= link_to 'Back', presences_index_path %>